# config/sidekiq.yml
---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 4 } %>
:timeout: 30
:queues:
  - [low_priority, 1]
  - [default, 2]
  - [high_priority, 2] # high priority
:schedule:
  update_currency:
    every: [12h, first_in: 1m]  #run job each 12 hours
    class: UpdateCurrencyJob
    enable: true
    queue: high_priority
    description: petition for update data in model currency

  update_deals_test:
<<<<<<< HEAD
    every: [24h, first_in: 2m]
    class: CreateClusterJob
=======
    every: [12h, first_in: 1m]
    class: CreateOffersJob
>>>>>>> optimize_code
    enable: true
    queue: default
    description: test job
