# config/sidekiq.yml
---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
:queues:
  - [low_priority, 1]
  - [high_priority, 2] # high priority
:schedule:  
  update_currency: 
    every: [12h, first_in: 1m]  #run job each 12 hours
    class: UpdateCurrencyJob
    enable: true
    queue: high_priority
    description: petition for update data in model currency
    
  update_deals_us: 
    every: [24h, first_in: 2m]  #run job each 12 hours
    class:  UpdatedealsusaJob 
    enable: true
    queue: high_priority
    description: petition for update data in model sale
    
  update_deals_cl: 
    every: [24h, first_in: 4m]  #run job each 12 hours
    class:  UpdatedealsclJob 
    enable: true
    queue: high_priority
    description: petition for update data in model sale

  update_deals_ar: 
    every: [24h, first_in: 6m]  #run job each 12 hours
    class:  UpdatedealsarJob 
    enable: true
    queue: high_priority
    description: petition for update data in model sale
    
